server:
  port: 8080
  servlet:
    context-path: /
#  ssl:
#    enabled: true


spring:
  profiles:
    active: '@spring.profiles.active@'
  jackson:
#    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES

logging:
  level:
    root: info
#    web: debug
#    com.oceanpayment.opgateway.common.config.datasource: debug  #数据源
#    com.oceanpayment.opgateway.controller: debug  #controller层
#    com.oceanpayment.opgateway.service: debug  #service层
#    com.oceanpayment.opgateway.mapper: debug  #mapper层

# ================= Mybatis =================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.oceanpayment.opgateway.pojo.entity
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

# ================= PageHelper =================
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  offsetAsPageNum: true
  rowBoundsWithCount: true

# ================= Swagger =================
springfox:
  documentation:
    swagger-ui:
      enabled: true

