server:
  port: 8080
  servlet:
    context-path: /


spring:
  profiles:
    active: dev


logging:
  level:
    root: info
#    web: debug
#    com.oceanpayment.opgateway.common.config.datasource: debug  #数据源
#    com.oceanpayment.opgateway.controller: debug  #controller层
#    com.oceanpayment.opgateway.service: debug  #service层
#    com.oceanpayment.opgateway.mapper: debug  #mapper层

# ================= Mybatis =================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.oceanpayment.opgateway.pojo.entity
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true




---
spring:
  profiles: dev
  # ================= Redis =================
  redis:
    host: 127.0.0.1
    port: 6379
  # ================= 数据源 =================
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.11.155:1521:pdbdev
    username: ccps
    password: Dev_PtNz2021

